<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>CustomerWeb</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Client\**" />
    <Content Remove="Client\**" />
    <EmbeddedResource Remove="Client\**" />
    <None Remove="Client\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Client\CustomerWeb.Client.csproj" />
  </ItemGroup>

</Project>
