<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Database\DotNetMonoRepoTemplate.Database.csproj" />
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Cache\DotNetMonoRepoTemplate.Cache.csproj" />
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Logging\DotNetMonoRepoTemplate.Logging.csproj" />
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Observability\DotNetMonoRepoTemplate.Observability.csproj" />
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Email\DotNetMonoRepoTemplate.Email.csproj" />
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Utilities\DotNetMonoRepoTemplate.Utilities.csproj" />
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Types\DotNetMonoRepoTemplate.Types.csproj" />
    <ProjectReference Include="..\..\..\..\common\DotNetMonoRepoTemplate.Export\DotNetMonoRepoTemplate.Export.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Otp.NET" />
    <PackageReference Include="QRCoder" />
  </ItemGroup>

</Project>
